dataset_name: PCQM4Mv2
batch_size: 256
num_workers: 6
lr: 1e-3
min_lr: 1e-6
l2_wd: 1e-5
num_epochs: 350
num_warmup_epochs: 20
emb_channels: 32
hidden_channels: 512
num_layers: 10
mlp_depth: 2
norm_type: Batch
drop_prob: 0.0
graph_pool: avg
jumping_knowledge: last
degree_rescalling: False
task_type: graph_regression
num_task: 1
pe_method: bern_mixed_smooth
pe_power: 24
test_eval_interval: 10
