dataset_name: Functional
batch_size: 16
num_workers: 4
lr: 3e-4
min_lr: 1e-6
l2_wd: 1e-5
num_epochs: 200
num_warmup_epochs: 10
hidden_channels: 96
num_layers: 4
mlp_depth: 2
norm_type: Batch
drop_prob: 0.2
graph_pool: avg
jumping_knowledge: last
task_type: graph_classification
num_task: 10
runs: 5
pe_method: bern_mixed_sym2
pe_power: 24
test_eval_interval: 10
